### ISSUE TITLE
API use from GitHub or GitLab for gpic will contribute to rate limits, improve this situation

### ISSUE THREAD

**Issue by FelicianoTech** [revidian-cloud/go-gravatar#28]
Some form of caching/avoiding API calls when possible should be implemented.

**Comment by FelicianoTech** [comment]
@chayev I would like this to be complete when or near I implement GitHub profile photos in RepoWarden. Is this something you're interested in tackling or shall I?

**Comment by chayev** [comment]
Awesome. This is a great feature. I think you should take it. Won't be able to look into this until later this week.
